//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XBSlink.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XBSlink.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\colortbl ;\red0\green0\blue255;}
        ///{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\f0\fs24\lang9\par
        ///
        ///\pard\sa200\sl276\slmult1\fs32\cf0\cb2\b\ul\i\ulc0\caps\expndtw2\f1\expndtw5\insrsid10057350 Thexgamelord&apos;s XBSlink Fixer\cf0\cb1\b0\ulnone\i0\ulc0\par
        ///\par
        ///
        ///\fs24\cf0\cb2\ul\i\ulc0\expndtw0\f1 Introduction\cf0\cb1\ulnone\i0\ulc0\expndtw6\par
        ///XBSlink is an exciting gaming tool tha [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about_xbslink {
            get {
                return ResourceManager.GetString("about_xbslink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, XBSlink crashed.
        ///Please send this info to thexgamelord@hotmail.com, we might have the right bug spray ;) Thank you!.
        /// </summary>
        internal static string crash_message {
            get {
                return ResourceManager.GetString("crash_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error_16 {
            get {
                object obj = ResourceManager.GetObject("error_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error_50 {
            get {
                object obj = ResourceManager.GetObject("error_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_key {
            get {
                object obj = ResourceManager.GetObject("icon_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XBSlink could not find any capture devices in your system.
        ///This problem occurs if the WinPCap library is not active. Please make sure WinPCap is loaded.
        ///
        ///For more information see &lt;https://xbslink.thexgamelord.repl.co/xbslink/faq#question-15&gt;.
        /// </summary>
        internal static string message_no_capture_devices {
            get {
                return ResourceManager.GetString("message_no_capture_devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XBSlink could not find any capture devices in your system.
        ///This problem occurs if the WinPCap library is not active. Please make sure WinPCap is loaded.
        ///
        ///Do you want XBSlink to try starting the WinPcap driver (NPF) ?.
        /// </summary>
        internal static string message_no_capture_devices_startNPF {
            get {
                return ResourceManager.GetString("message_no_capture_devices_startNPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XBSlink could not find any capture devices in your system.
        ///This problem occurs if the user has not enough rights to use the pcap library. Please try to run XBSlink as root (&quot;sudo mono XBSlink.exe&quot;)
        ///
        ///For more information see &lt;https://xbslink.thexgamelord.repl.co/xbslink/faq#question-2&gt;.
        /// </summary>
        internal static string message_no_capture_devices_unix {
            get {
                return ResourceManager.GetString("message_no_capture_devices_unix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one MAC address to the list..
        /// </summary>
        internal static string message_specialmaclist_empty {
            get {
                return ResourceManager.GetString("message_specialmaclist_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XBSlink encountered at least one non-fatal error!
        ///Please check the messages..
        /// </summary>
        internal static string notifyicon_error_message {
            get {
                return ResourceManager.GetString("notifyicon_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XBSlink encountered at least one fatal error! 
        ///Please check the messages..
        /// </summary>
        internal static string notifyicon_fatal_error_message {
            get {
                return ResourceManager.GetString("notifyicon_fatal_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XBSlink encountered at least one warning!
        ///Please check the messages..
        /// </summary>
        internal static string notifyicon_warning_message {
            get {
                return ResourceManager.GetString("notifyicon_warning_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok_16 {
            get {
                object obj = ResourceManager.GetObject("ok_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://xbslink.thexgamelord.repl.co/xbslink/latest_xbslink_version.
        /// </summary>
        internal static string url_check_latest_version {
            get {
                return ResourceManager.GetString("url_check_latest_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://xbslink.thexgamelord.repl.co/xbslink/latest_xbslink_version_linux.
        /// </summary>
        internal static string url_check_latest_version_linux {
            get {
                return ResourceManager.GetString("url_check_latest_version_linux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://xbslink.thexgamelord.repl.co/xbslink/latest_xbslink_version_mac.
        /// </summary>
        internal static string url_check_latest_version_mac {
            get {
                return ResourceManager.GetString("url_check_latest_version_mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://xbslink.thexgamelord.repl.co/xbslink/.
        /// </summary>
        internal static string url_xbslink_website {
            get {
                return ResourceManager.GetString("url_xbslink_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning_16 {
            get {
                object obj = ResourceManager.GetObject("warning_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon XBSlink {
            get {
                object obj = ResourceManager.GetObject("XBSlink", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
